import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./_Components/Footer/Footer";
import "@fortawesome/fontawesome-free/css/all.css";
import { Toaster } from "@/components/ui/sonner";
import UserProvider from "src/UserProvider";
import CountProvider from "src/CountProvider";
import Navbar from "./_Components/Navbar/Navbar";

const Encode_SansFont = Encode_Sans({
  weight: ["100", "400", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_SansFont.className}, font-family `}>
        <UserProvider>
          <CountProvider>
            <Navbar />
            <main className="p-5 w-11/12 mx-auto ">{children}</main>
            <Toaster />
            <Footer />
          </CountProvider>
        </UserProvider>
      </body>
    </html>
  );
}
