import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@fortawesome/fontawesome-free/css/all.css";
import { Toaster } from "@/components/ui/sonner";
import UserProvider from "src/UserProvider";

import Navbar from "./_Components/Navbar/Navbar";
import { WishlistProvider } from "src/WishListProvider";
import CountProvider from "src/CountProvider";



const Encode_SansFont = Encode_Sans({
  weight: ["100", "400", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <UserProvider>
          
          <CountProvider>
            <WishlistProvider>
              
                <Navbar />
                <main className="mx-auto pt-5 mt-5 overflow-hidden">{children}</main>
                <Toaster className="bg-main"/>
              
            </WishlistProvider>
          </CountProvider>
          
        </UserProvider>
      </body>
    </html>
  );
}
